# Generated by Django 3.1.5 on 2021-03-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=1000)),
                ('c_code', models.TextField()),
                ('java_code', models.TextField()),
                ('program_description', models.TextField()),
                ('python_code', models.TextField()),
                ('output', models.TextField()),
                ('program_visibility', models.BooleanField(default=False)),
            ],
        ),
    ]
