# Generated by Django 3.1.5 on 2021-03-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='program_link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
