# Generated by Django 3.1.5 on 2021-02-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningprojects',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='machinelearningprojects',
            name='source_file',
            field=models.FileField(upload_to='pics'),
        ),
    ]
